### ISSUE TITLE
more deprecations 

### ISSUE THREAD

**Issue by Fivell** [ianfleeton/paypal-express#11]
@ianfleeton , hello , detected more warnings when testing sdk. 

when updating billing agreement , response may include payee info

they are not handled in the moment.

```
.......................W, [2017-03-20T17:41:24.002210 #44937]  WARN -- Paypal::Express: Ignored Parameter (Paypal::Express::Response): PAYEEEMAIL=********
W, [2017-03-20T17:41:24.002263 #44937]  WARN -- Paypal::Express: Ignored Parameter (Paypal::Express::Response): PAYEREID=*****

```

References 
https://github.com/ianfleeton/paypal-express/blob/master/lib/paypal/express/request.rb#L157
https://developer.paypal.com/docs/classic/api/merchant/BAUpdate_API_Operation_NVP/#payeeinfotype-fields

Second one is 
RefundTransaction method, that returns REFUNDSTATUS

```
 WARN -- Paypal::Express: Ignored Parameter (Paypal::Exception::APIError::Response): REFUNDSTATUS=None
```

**Comment by ianfleeton** [comment]
Thanks, I'll take a look at these next week.

**Comment by ianfleeton** [comment]
@fivell I'm looking into the PayeeInfo response. Please can you give me a sample request (e.g., in code) for updating the billing agreement so I can get the tests in a realistic context.

**Comment by Fivell** [comment]
@ianfleeton , example for token revoke response
```
BILLINGAGREEMENTID=AGREEMENT_ID&BILLINGAGREEMENTDESCRIPTION=some%20desc%202&BILLINGAGREEMENTSTATUS=Canceled&TIMESTAMP=2017%2d03%2d05T09%3a31%3a13Z&CORRELATIONID=bd8b116082611&ACK=Success&VERSION=204%2e0&BUILD=30029726&EMAIL=developers%40didww%2ecom&PAYERID=URXM7BK7RWB52&PAYERSTATUS=verified&BUSINESS=company&FIRSTNAME=fistname&LASTNAME=lastname&COUNTRYCODE=US&ADDRESSID=PayPal&PAYEEEMAIL=seller_1305369137_biz%40matake%2ejp&PAYEEID=YU5ZSGSMQB2WE
```

**Comment by ianfleeton** [comment]
Thanks, please can you also provide some request code (in Ruby using this API) that might give a billing agreement response like that.

I'm asking as I haven't used this part of the API and need to set up a realistic request to go with it for testing.

**Comment by Fivell** [comment]
@ianfleeton , here it is  
```
::Paypal::Express::Request.new(CONFIG[:paypal][:express]).revoke!('AGREEMENT_ID')
```

**Comment by ianfleeton** [comment]
Aha yes, thanks!

**Comment by Fivell** [comment]
@ianfleeton , sorry for noise here, but there is one more.

when calling GetExpressCheckoutDetails method , response can also include ```ADDRESSNORMALIZATIONSTATUS```
like 
```
ADDRESSNORMALIZATIONSTATUS=None
```

UPD ignore this looks like it was merged , I will update gem to master and test one more time

**Comment by Fivell** [comment]
@ianfleeton , looks good, last thing is 
RefundTransaction method, that returns REFUNDSTATUS
[2017-04-13T16:06:46.499893 #22736]  WARN -- Paypal::Express: Ignored Parameter (Paypal::Exception::APIError::Response): REFUNDSTATUS=None

**Comment by ianfleeton** [comment]
@fivell looks like this was also fixed in #9 and you're missing the commit in your fork

https://github.com/ianfleeton/paypal-express/commit/c74ea22b314eb9b75e6b72aa400752203d8d7ae5

I'll close this for now, let me know if I'm missing anything.

**Comment by Fivell** [comment]
@ianfleeton , it fixed only for successful case 

There is a failing case also. 

take a look at this line https://github.com/ianfleeton/paypal-express/blob/master/lib/paypal/nvp/request.rb#L59


we have 
```
Exception::APIError.new(response)
```
response example

```
{:TIMESTAMP=>"2017-03-01T16:17:13Z", :CORRELATIONID=>"ec17e6541628a", :ACK=>"Failure", :VERSION=>"204.0", :BUILD=>"30763207", :L_ERRORCODE0=>"10009", :L_SHORTMESSAGE0=>"Transaction refused", :L_LONGMESSAGE0=>"This transaction has already been fully refunded", :L_SEVERITYCODE0=>"Error", :REFUNDSTATUS=>"None", :PENDINGREASON=>"None"}
```
and it doesn't handle ```REFUNDSTATUS```

**Comment by ianfleeton** [comment]
Hmm, I'll have a think at how to weave it into the error response. Thanks for the response example.

**Comment by ianfleeton** [comment]
@fivell thanks for your patience, please can you now check master works correctly for you. The refund status should now be on the response object of the raised API error.

**Comment by Fivell** [comment]
@ianfleeton, no warnings now while my test  suite. 👍 , thanks
