### ISSUE TITLE
I get an "undefined method, 'checkout!'" error when executing "DoExpressCheckoutPayment"

### ISSUE THREAD

**Issue by leather-s** [ianfleeton/paypal-express#12]
Hello, @ianfleeton 

I get the following error when executing my success callback code
![image](https://cloud.githubusercontent.com/assets/19522903/24226171/2b5c67ce-0f22-11e7-9002-8d895aada248.png)

what info exactly do I include in that variable "payment_request"?

**Comment by leather-s** [comment]
Hello, @ianfleeton 

I get the following error when executing my success callback code
![image](https://cloud.githubusercontent.com/assets/19522903/24226171/2b5c67ce-0f22-11e7-9002-8d895aada248.png)

what info exactly do I include in that variable "payment_request"?

**Comment by ianfleeton** [comment]
It looks as though you haven't created a PayPal Express request in that action.

There happens to still be a variable called request that is available through your controller, and it's this one that is complaining. (There's also another called response!) There's a clue to this in the class name ActionDispatch::Request in the error.

Using request and response as local variables in your Rails controller action will shadow those provided by the controller. You can remove confusion by naming your variables something like paypal_request and paypal_response.

**Comment by leather-s** [comment]
Thank you so much! 

For anyone who sees this... It is necessary to pass the credentials and the amount in the second confirmation request that gets sent from the success action.
