### ISSUE TITLE
gem 'paypal-express', github: 'ianfleeton/paypal-express' fails

### ISSUE THREAD

**Issue by G0dwin** [ianfleeton/paypal-express#13]
When I include 

```ruby
gem 'paypal-express', github: 'ianfleeton/paypal-express'
```

In my `Gemfile` I get the following error on `bundle install`:

```bash
Could not find gem 'paypal-express' in https://github.com/ianfleeton/paypal-express (at master@285f6ec).
Source does not contain any versions of 'paypal-express'
```
It looks like this is because `paypal-express.gemspec` was renamed to `ianfleeton-paypal-express.gemspec`. 

Using:

```ruby
gem 'ianfleeton-paypal-express', require: 'paypal/express'
```

does work, it looks like the project needs both `ianfleeton-paypal-express.gemspec` and `paypal-express.gemspec` files.

**Comment by ianfleeton** [comment]
Good catch @G0dwin. I renamed the gem today. I've just updated the README, let me know if it doesn't fix the issue for you. (Note the require parameter is also needed now.)
