### ISSUE TITLE
Wiki's debugging example does not work

### ISSUE THREAD

**Issue by 5t111111** [ianfleeton/paypal-express#14]
Thanks for forking an inactive project and keeping maintenance!

In Wiki, there's an article about debugging API requests.

https://github.com/ianfleeton/paypal-express/wiki/Debugging

However, since the recent releases of Rails (Active Support) no longer support `alias_method_chain`, that example does not work.

I think it's good idea to rewrite it using `prepend` instead of `alias_method_chain` like:

```ruby
module Paypal
  module NVP
    module Debugger
      def post(method, params = {})
        response = super

        puts <<-DEBUG
#{method}
==========
#{params.to_query}
----------
#{response}
==========

DEBUG
        response
      end
    end

    class Request
      prepend Debugger
    end
  end
end
```

How does this sound to you?

**Comment by ianfleeton** [comment]
Hey, thanks for noticing and suggesting a fix. In fact I'm not sure and need to read that part of the wiki and the manual on prepend. When I understand it I'll make the change!

**Comment by ianfleeton** [comment]
I've read through and now understand your changes. It works well so I've updated the wiki. Thanks for your contribution!
