### ISSUE TITLE
Notify Url for recurring payments

### ISSUE THREAD

**Issue by amitej1** [ianfleeton/paypal-express#15]
Is there any place we can input notify_url for recurring payments? While the recurring profile gets set up properly, there is no way to extract transaction ids.

**Comment by ianfleeton** [comment]
There does not appear to be.

Looking at the code comments, there's one stating: "recurring payment doesn't support dynamic notify_url".

If this is not correct [anymore], please can you paste a link to PayPal documentation. Would you be willing to look at a patch & tests if this is the case?
