### ISSUE TITLE
Is 88 version deprecated ?

### ISSUE THREAD

**Issue by kannancet** [ianfleeton/paypal-express#17]
@ianfleeton - I have been using version 88 and the `nov/paypal-express` gem on my payment APIs. Is this version deprecated. Is it the reason you have create a fork ? So far we haven't experienced any issues, so would be very helpful to know your feedback to consider upgrading to your fork.

**Comment by ianfleeton** [comment]
Hi @kannancet - I believe it can still work, though @hevamb mentions in nov/paypal-express#74 that PayPal said it was a bit old and a newer version should be used. Newer versions of the API required that the api version desired was sent with existing requests. See EnyukaStudio/paypal-express#1 for the start of that.

If you are experiencing no issues, then good for you! However, I believe nov stopped maintaining his version after he stopped using PayPal, which means it's no longer tested against newer rubies, Rails, etc. It also lacks a few tweaks and fixes, such as support for phone numbers.

The reason I created the fork is I needed PRs from multiple contributors that weren't being merged into nov's version.

This fork is a conservative maintenance fork so it should also work for you and I'm happy to apply any pull requests for fixes and features, so long as they come with tests and are not disruptive or too idiosyncratic.

Cheers!
