### ISSUE TITLE
Paypal sandbox not reflecting transactions

### ISSUE THREAD

**Issue by SachinDev108** [ianfleeton/paypal-express#18]
Hi @ianfleeton,
Could please help me, 
On https://developer.paypal.com/developer/accounts/ I have 2 sandbox accounts:
- [business] abc-facilitator@domain.com
- [personal] abc-buyer@domain.com

Then in the sandbox paypal store I login successfully with the buyer's account and click the continue button representing payment. I'm successfully redirected back to my success_url and receive what look like some successful params:

      /orders/success/6 token=SAME_TOKEN_FROM_PAYPAL_AS_THE_ONE_ABOVE&PayerID=THE_PAYER_ID_OF_SANDBOX_BUYER_ACCOUNT

Ok so cool the transaction is finished but when I log into the sandbox paypal site with either the buyer or seller's login details, no transactions are listed. When I'm logged into my main paypal developer account, I also cannot see any transactions.

**Comment by ianfleeton** [comment]
@SachinDev108 my guess is that the transaction is not complete. Did you call DoExpressCheckoutPayment with the token and payer ID in the success URL as described in https://github.com/ianfleeton/paypal-express/wiki/Instant-Payment?

**Comment by SachinDev108** [comment]
Thanks @ianfleeton  for reply

I did only below changes
paypal_options = {
  no_shipping: true, # if you want to disable shipping information
  allow_note: false, # if you want to disable notes
  pay_on_paypal: true # if you don't plan on showing your own confirmation step
}

request = Paypal::Express::Request.new(
  :username   => SET_YOUR_OWN,
  :password   => SET_YOUR_OWN,
  :signature  => SET_YOUR_OWN
)
payment_request = Paypal::Payment::Request.new(
  :currency_code => :JPY,   # if nil, PayPal use USD as default
  :description   => FOO,    # item description
  :quantity      => 1,      # item quantity
  :amount        => 1.00,   # item value
  :custom_fields => {
    CARTBORDERCOLOR: "C00000",
    LOGOIMG: "https://example.com/logo.png"
  }
)
response = request.setup(
  payment_request,
  YOUR_SUCCESS_CALLBACK_URL,
  YOUR_CANCEL_CALLBACK_URL,
  paypal_options  # Optional
)
response.redirect_uri

Could you please correct me what I missed

**Comment by SachinDev108** [comment]
Got your point @ianfleeton and thank you so much :)
I need to right this code in my success path 
Is am right ?

response = request.checkout!(
  token,
  payer_id,
  payment_request
)
response.payment_info

**Comment by ianfleeton** [comment]
Yes, that's it. :)
