### ISSUE TITLE
deprecated API used

### ISSUE THREAD

**Issue by daddyz** [ianfleeton/paypal-express#21]
You should write that [deprecated API](https://developer.paypal.com/docs/classic/express-checkout/gs_transaction/) is used in gem.
We have transactions that are coming from "verified" payer by GetTransaction method, while they are unverified actually.

**Comment by ianfleeton** [comment]
Thanks daddyz.

Having a bit more of a look around it seems that Express Checkout in general is deprecated, not just a handful of the API calls. The customer guides don't mention it:

https://www.paypal.com/ba/webapps/mpp/express-checkout

But the developer docs do:

https://developer.paypal.com/docs/classic/express-checkout/ec_api_flow/

WDYT?

If that's the case I'll put a big warning on the README and put the project in maintenance mode.

**Comment by daddyz** [comment]
We (as a company) have contacted PayPal in order to clarify things, their new API does not support verified status for payer at all. As they said, even in their UI verified (or not) is not reflected properly unlike the old (deprecated) API. Currently we are still using this gem and awaiting for several replies from PayPal on this matter. In new API there is a "seller protection" param which probably should replace the "verified" payer status, but it's still unclear.
I say just put warning on readme page in order to notify your users on this matter.

**Comment by ianfleeton** [comment]
Hi, thanks for the update. If you can do a PR with the exact wording updates in the README that would be great and I'll merge it right in. If not I'll have a go a bit later.
